### ISSUE TITLE
Let me do multiple commands

### ISSUE THREAD

**Issue by vihanb** [The-Quill/SE-Chat-Terminal#12]
If I'm in a room and seeing messagse

<img width="682" alt="screen shot 2016-02-26 at 8 18 23 pm" src="https://cloud.githubusercontent.com/assets/15314511/13376871/56f345da-dd7b-11e5-80c3-08d29e891832.png">

I would like to be able to send a message or enter a command.

**Comment by The-Quill** [comment]
Working on a fix at the moment, but I can't find a pretty solution besides recursion

**Comment by The-Quill** [comment]
Fixed in #35
