### ISSUE TITLE
Fix prompting appearing after connection text

### ISSUE THREAD

**Issue by The-Quill** [The-Quill/SE-Chat-Terminal#3]
I tried promises, but websockets never actually resolve, so it's kinda messed up

**Comment by The-Quill** [comment]
I pinged @DanPantry about this, I'll ask for his help with it

**Comment by danpantry** [comment]
I'll take a look in a few hours.

**Comment by RikerW** [comment]
@The-Quill Sorry I created another issue accidentally.  I didn't realize my problem was about the prompting.  You can close/merge.

**Comment by The-Quill** [comment]
@RikerW you were actually referencing a different issue, they're related, just not the same (siblings, maybe?)

**Comment by RikerW** [comment]
I see what this problem is.  Yeah, it  is annoying to have your words cut off mid-command.

**Comment by The-Quill** [comment]
Fixed in #35
