### ISSUE TITLE
Password storage in rc or profile is not secure

### ISSUE THREAD

**Issue by VTCAKAVSMoACE** [The-Quill/SE-Chat-Terminal#36]
Rather than putting it in a readable file, ask for it during execution (not on the execution of start.js) through STDIN or equivalent.

**Comment by The-Quill** [comment]
http://chat.stackexchange.com/transcript/message/29664376#29664376

**Comment by The-Quill** [comment]
Optional password and username piping... means I may have to ditch the idea of config in general... CC #33
