### ISSUE TITLE
HTML to Markdown converter

### ISSUE THREAD

**Issue by The-Quill** [The-Quill/SE-Chat-Terminal#37]
Ewwwww... gotta do it though.

**Comment by VTCAKAVSMoACE** [comment]
See: [to-markdown](https://github.com/domchristie/to-markdown)

**Comment by The-Quill** [comment]
@VTCAKAVSMoACE Borked for my version of Node... I just wrote a shitty implementation

**Comment by The-Quill** [comment]
Fixed in b15eea22e5ac277cc7a3538d534259cb0605cf77
