### ISSUE TITLE
Commands have arguments (so no prompting for everything)

### ISSUE THREAD

**Issue by RikerW** [The-Quill/SE-Chat-Terminal#43]
I want to run `/say SE 240 "foo"` and have it say "foo" in room 240 of SE. But right now it errors with a undefined command name.

Maybe split on spaces for command arguments?

**Comment by vihanb** [comment]
This is a bug not an enhancement right?

**Comment by The-Quill** [comment]
@vihanb it never was the intended usage of that.... that's why it throws an error.

**Comment by vihanb** [comment]
oh
